# Generated by Django 3.2.7 on 2022-07-03 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0040_auto_20220702_2027'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackerapplication',
            name='wustl_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mentorapplication',
            name='wustl_student',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hackerapplication',
            name='online',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='mentorapplication',
            name='online',
            field=models.BooleanField(default=True),
        ),
    ]
