# Generated by Django 3.2.7 on 2022-07-09 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_loginrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_wustl',
            field=models.BooleanField(default=False),
        ),
    ]
